[news]
title = "빌보드 코리아 ─ 뉴스"
url = "http://billboard.co.kr/main/news/list"
entrySelector = "ul.clr.news li"
titleSelector = "div.txt span"
linkSelector = "a"
imageSelector = "div.img-con img"
waitUntil = "networkidle"
onFail = "stale"

[main]
title = "빌보드 코리아 ─ 메인"
url = "http://billboard.co.kr/main/"
entrySelector = "div[class^='swiper-slide vi_item'] a.vi_item_link"
titleSelector = "div.txt_wrap h3"
linkSelector = "*"
contentSelector = "div.txt_wrap p"
imageSelector = "div.img_wrap img"
waitUntil = "networkidle"

[main_news]
title = "빌보드 코리아 ─ 메인 ─ 뉴스"
url = "http://billboard.co.kr/main/"
entrySelector = "div.main_news.main_news02 div.inner ul.clr.news_list li"
titleSelector = "a div.txt div.ttl"
linkSelector = "a"
contentSelector = "a div.txt div.ttl"
imageSelector = "div.img img"
waitUntil = "networkidle"
